services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - ince
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file: .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/html
    networks:
      - ince
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - ince
    restart: always
  redis:
    container_name: redis
    image: redis
    build: ./bonus/redis
    networks:
      - ince
    restart: always
    env_file:
      - .env
  adminer:
    container_name: adminer
    image: adminer
    build: ./bonus/Adminer
    networks:
      - ince
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
  ftp-server:
    container_name: ftp-server
    image: ftp-server
    build: ./bonus/ftp-server
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - ince
    restart: always
    env_file:
      - .env
  website:
    container_name: website
    image: website
    build: ./bonus/website
    networks:
      - ince
    restart: always
  cadvisor:
    container_name: cadvisor
    image: cadvisor
    build: ./bonus/cadvisor
    networks:
      - ince
    volumes:
      - "/:/rootfs:ro"     
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
    restart: always

networks:
  ince:
    name: ince

volumes:
  mariadb:
      name: mariadb
      driver: local
      driver_opts:
        device: /home/bamssaye/data
        o: bind
        type: none
  wordpress:
      name: wordpress
      driver : local
      driver_opts:
        device: /home/bamssaye/data
        o: bind
        type: none


#sudo rm -rf /home/bihix/data/*
#docker exec mariadb  cat  /etc/my.cnf.d/mariadb-server.cnf
#docker exec -it mariadb  mariadb -u root -p$DB_PASSWORD